title: "Marcelo Gallardo"
email: marcelo.gallardob@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website!
baseurl: "/" 
url: "https://MarceloGallardoB.github.io/" 
twitter_username: 
github_username:  MarceloGallardoB

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
